name: Npm Latest Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
